### ISSUE TITLE
omprog: failed to execute binary '/opt/fancy': Permission denied

### ISSUE THREAD

**Issue by y0tsawin** [negbie/fancy#2]
omprog: failed to execute binary '/opt/fancy': Permission denied

**Comment by negbie** [comment]
Hi @y0tsawin could you show me the output of ls -al /opt/fancy

**Comment by negbie** [comment]
You need to make sure that rsyslog has the permissions to execute it.

**Comment by y0tsawin** [comment]
ls -al /opt/fancy
total 80
drwxr-xr-x 5 root root  4096 Oct 29 15:56 .
drwxr-xr-x 5 root root  4096 Oct 29 15:56 ..
drwxr-xr-x 4 root root  4096 Oct 29 15:56 example
drwxr-xr-x 8 root root  4096 Oct 29 15:56 .git
-rwxr-xr-x 1 root root   267 Oct 29 15:56 go.mod
-rwxr-xr-x 1 root root  8366 Oct 29 15:56 go.sum
-rwxr-xr-x 1 root root 11343 Oct 29 15:56 LICENSE
-rwxr-xr-x 1 root root   823 Oct 29 15:56 logline.go
drwxr-xr-x 2 root root  4096 Oct 29 15:56 logproto
-rwxr-xr-x 1 root root  4361 Oct 29 15:56 loki.go
-rwxr-xr-x 1 root root  4793 Oct 29 15:56 main.go
-rwxr-xr-x 1 root root  1456 Oct 29 15:56 parse.go
-rwxr-xr-x 1 root root  1650 Oct 29 15:56 parse_test.go
-rwxr-xr-x 1 root root  1259 Oct 29 15:56 README.md

**Comment by negbie** [comment]
/opt/fancy is in your case a directory but omprog expects the binary there.

**Comment by y0tsawin** [comment]
binary="/opt/fancy --loki-url http://192.168.0.122:3100" 
Can you recommend. How do I have to config omprog ?

**Comment by negbie** [comment]
Just make sure the fancy binary is in /opt
So when you run ls -al /opt/fancy you should see something like this:
-rwxr-xr-x 1 negbie negbie 3311828 Oct 27 21:07 /opt/fancy

In rsyslog.conf you can set this:

action(type="omprog" name="fancy" template="fancy" output="/var/log/fancy.log" binary="/opt/fancy --loki-url http://192.168.0.122:3100")

**Comment by negbie** [comment]
But you have downloaded the binary from releases https://github.com/negbie/fancy/releases right?

**Comment by negbie** [comment]
Btw. I have uploaded a rsyslog.conf example too here: https://github.com/negbie/fancy/blob/master/example/rsyslog/rsyslog.conf

**Comment by negbie** [comment]
Would you say my setup guide here https://github.com/negbie/fancy#setup is not clear enough and I should improve it?

**Comment by y0tsawin** [comment]
I have done as you suggest. 

ls -al 
-rwxr-xr-x 1 root root 3311812 Oct 27 04:24 fancy

rsysconf.conf
module(load="omprog")
$template fancy,"%syslogseverity% %hostname% %programname%%msg%\n"
action(type="omprog" name="fancy" template="fancy" output="/var/log/fancy.log" binary="/opt/fancy --loki-url http://192.168.1.122:3100")

**Comment by negbie** [comment]
Good, do you still need help?

**Comment by y0tsawin** [comment]
Can I use this file instead of the original file?

https://github.com/negbie/fancy/blob/master/example/rsyslog/rsyslog.conf

**Comment by negbie** [comment]
You will need to make some adjustments but basicly yes.

**Comment by negbie** [comment]
@y0tsawin Do you still need help or can I close this issue?

**Comment by negbie** [comment]
@y0tsawin attention, version 1.6 is up and requires a different template. Please see readme.

**Comment by negbie** [comment]
New template should look like this for version 1.6:

$template fancy,"%timegenerated:::date-rfc3339% %syslogseverity% %hostname% %programname%%msg%\n"

**Comment by y0tsawin** [comment]
Good. It work.
Thank you for your support.

**Comment by negbie** [comment]
Your welcome. Don't forget to give this project a start if you like it. It's the best way to say thank you to a project on github.
