### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by eugenberend** [negbie/fancy#4]
Hi
I do not clearly understand which advantages has `fancy` over simply using omhttp and lokirest batch type. Could you please explain?
https://www.rsyslog.com/doc/master/configuration/modules/omhttp.html#example-5

**Comment by negbie** [comment]
Hi @eugenberend,
at the time I wrote fancy I didn't knew about omhttp. Beside the prometheus metrics which fancy can expose I don't think there is a advantage over omhttp.
